
/* Drop Tables */

DROP TABLE ADD_INGR CASCADE CONSTRAINTS;
DROP TABLE INFO_ORDER CASCADE CONSTRAINTS;
DROP TABLE ORDER CASCADE CONSTRAINTS;
DROP TABLE BUYER CASCADE CONSTRAINTS;
DROP TABLE CART_ADD_INGR CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE INGR CASCADE CONSTRAINTS;
DROP TABLE INQUIRY CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE MANAGER CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE MENU CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE ADD_INGR
(
	-- 추가 재료 번호
	ADD_INGR_NO number NOT NULL,
	INFO_ORDER_NO number NOT NULL,
	-- 소스번호
	-- 빵번호
	-- 야채번호
	INGR_NO varchar2(50) NOT NULL,
	PRIMARY KEY (ADD_INGR_NO)
);


CREATE TABLE BUYER
(
	-- 가맹점 번호
	BUYER_ID varchar2(100) NOT NULL,
	-- 가맹점 비밀번호
	BUYER_PW varchar2(100),
	-- 가맹점 이름
	BUYER_NAME varchar2(50),
	-- 가맹점 전화 번호
	BUYER_COMTEL varchar2(20),
	-- 가맹점 우편 번호
	BUYER_ZIP varchar2(10),
	-- 가맹점 주소
	BUYER_ADD varchar2(100),
	PRIMARY KEY (BUYER_ID)
);


CREATE TABLE CART
(
	CART_NO number NOT NULL,
	-- 회원ID
	MEM_ID varchar2(100) NOT NULL,
	-- 메뉴 분류 코드 작성 영역 시퀀스로 처리
	-- 
	MENU_NO number NOT NULL,
	CART_QTY number,
	PRIMARY KEY (CART_NO)
);


CREATE TABLE CART_ADD_INGR
(
	-- 장바구니 추가 재료 코드
	CART_ADD_NO number NOT NULL,
	-- 소스번호
	-- 빵번호
	-- 야채번호
	INGR_NO varchar2(50) NOT NULL,
	CART_NO number NOT NULL,
	PRIMARY KEY (CART_ADD_NO)
);


CREATE TABLE EVENT
(
	-- 이벤트 번호를 입력하는 영역
	EVENT_ID number NOT NULL,
	-- 관리자 아이디
	MANAGER_ID varchar2(100) NOT NULL,
	-- 이벤트 제목을 입력함.
	EVENT_TITLE varchar2(200) NOT NULL,
	-- 이벤트 시작 날짜 설정
	EVENT_STARTDATE date,
	-- 이벤트 종료 날짜 작성
	EVENT_ENDDATE date,
	-- 이벤트 내용을 작성하는 컬럼
	EVENT_CONTENTS varchar2(4000) NOT NULL,
	-- 이벤트 작성 일자
	EVENT_REG_DATE timestamp,
	PRIMARY KEY (EVENT_ID)
);


CREATE TABLE INFO_ORDER
(
	INFO_ORDER_NO number NOT NULL,
	-- 메뉴 분류 코드 작성 영역 시퀀스로 처리
	-- 
	MENU_NO number NOT NULL,
	ORDER_NO varchar2(50) NOT NULL,
	INFO_CART_QTY number,
	PRIMARY KEY (INFO_ORDER_NO)
);


CREATE TABLE INGR
(
	-- 소스번호
	-- 빵번호
	-- 야채번호
	INGR_NO varchar2(50) NOT NULL,
	INGR_GU varchar2(50),
	-- 빵이름
	-- 소스이름
	INGR_NAME varchar2(100),
	PRIMARY KEY (INGR_NO)
);


CREATE TABLE INQUIRY
(
	-- 1대1 문의번호
	-- 시퀀스로 작업 예정
	INQUIRY_NO number NOT NULL,
	-- 문의 제목 작성
	INQUIRY_TITLE varchar2(500) NOT NULL,
	-- 문의한 사용자의 이메일
	INQUIRY_EMAIL varchar2(60) NOT NULL,
	-- 연락 가능한 전화번호
	INQUIRY_COMETL varchar2(20) NOT NULL,
	-- 내용
	INQUIRY_CONTENT varchar2(4000) NOT NULL,
	-- 문의 작성 일자
	INQUIRY_REG_DATE timestamp,
	PRIMARY KEY (INQUIRY_NO)
);


CREATE TABLE MANAGER
(
	-- 관리자 아이디
	MANAGER_ID varchar2(100) NOT NULL,
	-- 관리자 비밀번호
	MANAGER_PW varchar2(100),
	-- 관리자 이름
	MANAGER_NAME varchar2(50),
	PRIMARY KEY (MANAGER_ID)
);


CREATE TABLE MEMBER
(
	-- 회원ID
	MEM_ID varchar2(100) NOT NULL,
	-- 비밀번호
	MEM_PW varchar2(100),
	-- 회원명
	MEM_NM varchar2(50),
	-- 생년월일
	MEM_REG_F varchar2(20),
	-- 회원 전화 번호
	MEM_NUMBER varchar2(20),
	-- 회원 우편 번호를 입력할 컬럼
	MEMBER_ZIP varchar2(10),
	-- 회원 주소를 입력할 영역
	MEMBER_ADD varchar2(1000),
	PRIMARY KEY (MEM_ID)
);


CREATE TABLE MENU
(
	-- 메뉴 분류 코드 작성 영역 시퀀스로 처리
	-- 
	MENU_NO number NOT NULL,
	-- 메뉴 이름 작성
	MENU_NM varchar2(200),
	-- 메뉴 재료 작성
	MENU_INGR varchar2(20),
	MENU_PRICE number,
	PRIMARY KEY (MENU_NO)
);


CREATE TABLE NOTICE
(
	-- 공지사항 번호 작성 시퀀스로 처리
	NOTICE_NO number NOT NULL,
	-- 관리자 아이디
	MANAGER_ID varchar2(100) NOT NULL,
	-- 공지사항 제목 작성
	NOTICE_TITLE varchar2(200),
	-- 공지 내용을 작성
	NOTICE_CONTENTS varchar2(4000),
	-- 공지 작성 일자
	NOTICE_REG_DATE timestamp,
	-- 상단에 노출할 중요 공지사항 코드
	-- 0 인 경우, 상단 노출 안함 
	-- 1 인 경우, 상단 노출 함
	NOTICE_IMPOR_CODE varchar2(5),
	PRIMARY KEY (NOTICE_NO)
);


CREATE TABLE ORDER
(
	ORDER_NO varchar2(50) NOT NULL,
	-- 가맹점 번호
	BUYER_ID varchar2(100) NOT NULL,
	-- 회원ID
	MEM_ID varchar2(100) NOT NULL,
	ORDER_PRICE number,
	-- 고객 주문 날짜
	ORDER_MEMBER_DATE timestamp,
	-- 가맹점 확인 시간
	ORDER_BUYER_CHOICE timestamp,
	PRIMARY KEY (ORDER_NO)
);



/* Create Foreign Keys */

ALTER TABLE ORDER
	ADD FOREIGN KEY (BUYER_ID)
	REFERENCES BUYER (BUYER_ID)
;


ALTER TABLE CART_ADD_INGR
	ADD FOREIGN KEY (CART_NO)
	REFERENCES CART (CART_NO)
;


ALTER TABLE ADD_INGR
	ADD FOREIGN KEY (INFO_ORDER_NO)
	REFERENCES INFO_ORDER (INFO_ORDER_NO)
;


ALTER TABLE ADD_INGR
	ADD FOREIGN KEY (INGR_NO)
	REFERENCES INGR (INGR_NO)
;


ALTER TABLE CART_ADD_INGR
	ADD FOREIGN KEY (INGR_NO)
	REFERENCES INGR (INGR_NO)
;


ALTER TABLE EVENT
	ADD FOREIGN KEY (MANAGER_ID)
	REFERENCES MANAGER (MANAGER_ID)
;


ALTER TABLE NOTICE
	ADD FOREIGN KEY (MANAGER_ID)
	REFERENCES MANAGER (MANAGER_ID)
;


ALTER TABLE CART
	ADD FOREIGN KEY (MEM_ID)
	REFERENCES MEMBER (MEM_ID)
;


ALTER TABLE ORDER
	ADD FOREIGN KEY (MEM_ID)
	REFERENCES MEMBER (MEM_ID)
;


ALTER TABLE CART
	ADD FOREIGN KEY (MENU_NO)
	REFERENCES MENU (MENU_NO)
;


ALTER TABLE INFO_ORDER
	ADD FOREIGN KEY (MENU_NO)
	REFERENCES MENU (MENU_NO)
;


ALTER TABLE INFO_ORDER
	ADD FOREIGN KEY (ORDER_NO)
	REFERENCES ORDER (ORDER_NO)
;



/* Comments */

COMMENT ON COLUMN ADD_INGR.ADD_INGR_NO IS '추가 재료 번호';
COMMENT ON COLUMN ADD_INGR.INGR_NO IS '소스번호
빵번호
야채번호';
COMMENT ON COLUMN BUYER.BUYER_ID IS '가맹점 번호';
COMMENT ON COLUMN BUYER.BUYER_PW IS '가맹점 비밀번호';
COMMENT ON COLUMN BUYER.BUYER_NAME IS '가맹점 이름';
COMMENT ON COLUMN BUYER.BUYER_COMTEL IS '가맹점 전화 번호';
COMMENT ON COLUMN BUYER.BUYER_ZIP IS '가맹점 우편 번호';
COMMENT ON COLUMN BUYER.BUYER_ADD IS '가맹점 주소';
COMMENT ON COLUMN CART.MEM_ID IS '회원ID';
COMMENT ON COLUMN CART.MENU_NO IS '메뉴 분류 코드 작성 영역 시퀀스로 처리
';
COMMENT ON COLUMN CART_ADD_INGR.CART_ADD_NO IS '장바구니 추가 재료 코드';
COMMENT ON COLUMN CART_ADD_INGR.INGR_NO IS '소스번호
빵번호
야채번호';
COMMENT ON COLUMN EVENT.EVENT_ID IS '이벤트 번호를 입력하는 영역';
COMMENT ON COLUMN EVENT.MANAGER_ID IS '관리자 아이디';
COMMENT ON COLUMN EVENT.EVENT_TITLE IS '이벤트 제목을 입력함.';
COMMENT ON COLUMN EVENT.EVENT_STARTDATE IS '이벤트 시작 날짜 설정';
COMMENT ON COLUMN EVENT.EVENT_ENDDATE IS '이벤트 종료 날짜 작성';
COMMENT ON COLUMN EVENT.EVENT_CONTENTS IS '이벤트 내용을 작성하는 컬럼';
COMMENT ON COLUMN EVENT.EVENT_REG_DATE IS '이벤트 작성 일자';
COMMENT ON COLUMN INFO_ORDER.MENU_NO IS '메뉴 분류 코드 작성 영역 시퀀스로 처리
';
COMMENT ON COLUMN INGR.INGR_NO IS '소스번호
빵번호
야채번호';
COMMENT ON COLUMN INGR.INGR_NAME IS '빵이름
소스이름';
COMMENT ON COLUMN INQUIRY.INQUIRY_NO IS '1대1 문의번호
시퀀스로 작업 예정';
COMMENT ON COLUMN INQUIRY.INQUIRY_TITLE IS '문의 제목 작성';
COMMENT ON COLUMN INQUIRY.INQUIRY_EMAIL IS '문의한 사용자의 이메일';
COMMENT ON COLUMN INQUIRY.INQUIRY_COMETL IS '연락 가능한 전화번호';
COMMENT ON COLUMN INQUIRY.INQUIRY_CONTENT IS '내용';
COMMENT ON COLUMN INQUIRY.INQUIRY_REG_DATE IS '문의 작성 일자';
COMMENT ON COLUMN MANAGER.MANAGER_ID IS '관리자 아이디';
COMMENT ON COLUMN MANAGER.MANAGER_PW IS '관리자 비밀번호';
COMMENT ON COLUMN MANAGER.MANAGER_NAME IS '관리자 이름';
COMMENT ON COLUMN MEMBER.MEM_ID IS '회원ID';
COMMENT ON COLUMN MEMBER.MEM_PW IS '비밀번호';
COMMENT ON COLUMN MEMBER.MEM_NM IS '회원명';
COMMENT ON COLUMN MEMBER.MEM_REG_F IS '생년월일';
COMMENT ON COLUMN MEMBER.MEM_NUMBER IS '회원 전화 번호';
COMMENT ON COLUMN MEMBER.MEMBER_ZIP IS '회원 우편 번호를 입력할 컬럼';
COMMENT ON COLUMN MEMBER.MEMBER_ADD IS '회원 주소를 입력할 영역';
COMMENT ON COLUMN MENU.MENU_NO IS '메뉴 분류 코드 작성 영역 시퀀스로 처리
';
COMMENT ON COLUMN MENU.MENU_NM IS '메뉴 이름 작성';
COMMENT ON COLUMN MENU.MENU_INGR IS '메뉴 재료 작성';
COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지사항 번호 작성 시퀀스로 처리';
COMMENT ON COLUMN NOTICE.MANAGER_ID IS '관리자 아이디';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '공지사항 제목 작성';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENTS IS '공지 내용을 작성';
COMMENT ON COLUMN NOTICE.NOTICE_REG_DATE IS '공지 작성 일자';
COMMENT ON COLUMN NOTICE.NOTICE_IMPOR_CODE IS '상단에 노출할 중요 공지사항 코드
0 인 경우, 상단 노출 안함 
1 인 경우, 상단 노출 함';
COMMENT ON COLUMN ORDER.BUYER_ID IS '가맹점 번호';
COMMENT ON COLUMN ORDER.MEM_ID IS '회원ID';
COMMENT ON COLUMN ORDER.ORDER_MEMBER_DATE IS '고객 주문 날짜';
COMMENT ON COLUMN ORDER.ORDER_BUYER_CHOICE IS '가맹점 확인 시간';



